name = "medium-backendhono"
main = "src/index.ts"
compatibility_date = "2024-11-11"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDM5MmE0M2UtMzA4OC00ZDQzLWIzYjAtMWJlNDQyNDE3OGIzIiwidGVuYW50X2lkIjoiZjc0OTQyNTAwMzlkYmQwODk4YzhiNDAwM2VhZTY2YjNmM2MwYzQ2Y2MyMzU1OGZjZDZiNjNjZDY4ZTExOWJmMCIsImludGVybmFsX3NlY3JldCI6IjIzYmQ5ODAzLWQ3MzUtNGMxZC1hMjdlLTVhYmVkNzIxZWM0OSJ9.zCj6yYRLLUTj2cH-JEmvPvotM1kx2E34xRIlbkRQrzc"
JWT_SECRET="SECRETHAIBHAI"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1